# Generated by Django 6.0.5 on 2026-06-22 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_code', models.CharField(db_index=True, help_text='例如：GB/T 1.1', max_length=50, verbose_name='标准代号与顺序号')),
                ('year_code', models.CharField(help_text='例如：2020', max_length=4, verbose_name='年代号')),
                ('cn_name', models.CharField(db_index=True, max_length=500, verbose_name='中文名称')),
                ('en_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='英文名称')),
                ('ics_code', models.CharField(blank=True, help_text='国际标准分类号', max_length=50, null=True, verbose_name='ICS 分类号')),
                ('ccs_code', models.CharField(blank=True, help_text='中国标准分类号', max_length=50, null=True, verbose_name='CCS 分类号')),
                ('publish_date', models.DateField(help_text='标准发布的日期', verbose_name='发布日期')),
                ('implement_date', models.DateField(help_text='标准开始实施的日期', verbose_name='实施日期')),
                ('replace_standard', models.CharField(blank=True, help_text='该标准代替的先前标准', max_length=200, null=True, verbose_name='代替标准号')),
                ('source_file', models.FileField(help_text='上传的原始文件（PDF 或 Word 格式）', upload_to='standards/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='原文件存储路径')),
                ('status', models.CharField(choices=[('pending', '待解析'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='解析状态')),
                ('error_reason', models.TextField(blank=True, help_text='解析失败时记录详细原因', null=True, verbose_name='失败原因备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '国家标准文档',
                'verbose_name_plural': '国家标准文档',
                'db_table': 'standard_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['standard_code'], name='standard_do_standar_58fd5f_idx'), models.Index(fields=['year_code'], name='standard_do_year_co_f0230c_idx'), models.Index(fields=['status'], name='standard_do_status_3ff76f_idx'), models.Index(fields=['cn_name'], name='standard_do_cn_name_5b4973_idx'), models.Index(fields=['-created_at'], name='standard_do_created_0228c1_idx')],
                'unique_together': {('standard_code', 'year_code')},
            },
        ),
    ]
