# Generated by Django 6.0.5 on 2026-06-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standarddocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standarddocument',
            name='source_base_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='源库std_base主键ID'),
        ),
        migrations.AddIndex(
            model_name='standarddocument',
            index=models.Index(fields=['source_base_id'], name='standard_do_source__2e83cd_idx'),
        ),
    ]
