# Generated by Django 6.0.5 on 2026-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_parser', '0002_alter_standarddocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddocument',
            name='extraction_source',
            field=models.CharField(blank=True, help_text='修订条目的提取方式：regex / llm / regex_fallback / failed', max_length=20, null=True, verbose_name='提取来源'),
        ),
        migrations.AddField(
            model_name='standarddocument',
            name='revision_changes',
            field=models.JSONField(blank=True, help_text='与上版标准相比的修订内容列表，格式：[{"index":"a","type":"增加","content":"..."}]', null=True, verbose_name='修订变化条目'),
        ),
    ]
